Repository sidorares/node-mysql2, pull requests merged in 2024-04, with the labels that each got.

#2542 fix(SSL): separate each certificate into an individual item
  lib/constants/ssl_profiles.js
Labels: high-priority

#2553 chore(website): update dependencies manually
  website/package-lock.json
  website/package.json
Labels: website

#2552 fix(docs): improve the contribution guidelines
  .nycrc
  Contributing.md
  codecov.yml
  package.json
Labels: documentation

#2572 fix(security): improve sanitization for big numbers support
  lib/parsers/binary_parser.js
  lib/parsers/text_parser.js
  test/esm/unit/parsers/big-numbers-strings-sanitization.test.mjs
  test/esm/unit/parsers/support-big-numbers-sanitization.test.mjs
Labels: enhancement, security

#2574 fix(security): improve results object creation
  .nycrc
  lib/parsers/binary_parser.js
  lib/parsers/text_parser.js
  test/common.test.cjs
  test/esm/unit/parsers/prototype-binary-results.test.mjs
  test/esm/unit/parsers/prototype-text-results.test.mjs
Labels: enhancement, security

#2591 fix: revert breaking change in results creation
  lib/helpers.js
  lib/parsers/binary_parser.js
  lib/parsers/text_parser.js
  test/esm/integration/parsers/execute-results-creation.test.mjs
  test/esm/integration/parsers/query-results-creation.test.mjs
  test/esm/unit/parsers/ensure-safe-binary-fields.test.mjs
  test/esm/unit/parsers/ensure-safe-text-fields.test.mjs
  test/esm/unit/parsers/prototype-binary-results.test.mjs
  test/esm/unit/parsers/prototype-text-results.test.mjs
Labels: security
