Repository sidorares/node-mysql2, pull requests merged in 2024-03, with the labels that each got.

#2462 Refactor: Squashed into one place some duplicated typescript declaration + typo fix
  test/tsc-build/helpers.ts
  typings/mysql/lib/protocol/packets/OkPacket.d.ts
  typings/mysql/lib/protocol/packets/index.d.ts
  typings/mysql/lib/protocol/sequences/ExecutableBase.d.ts
  typings/mysql/lib/protocol/sequences/QueryableBase.d.ts
  typings/mysql/lib/protocol/sequences/promise/ExecutableBase.d.ts
  typings/mysql/lib/protocol/sequences/promise/QueryableBase.d.ts
Labels: typescript

#2486 ci: report coverage data to Codecov
  .github/workflows/ci-coverage.yml
  .github/workflows/ci-osx.yml
Labels: in progress

#2487 docs: add badges for CI and Coverage rate
  README.md
  website/docs/index.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/index.mdx
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/index.mdx
Labels: documentation

#2494 chore: upgrade eslint-plugin-markdown
  .eslintrc
  package-lock.json
  package.json
Labels: dependencies

#2424 fix(cache): improve cache key serialization
  lib/parsers/parser_cache.js
  test/unit/parsers/cache-key-serialization.js
Labels: enhancement

#2533 docs: remove RDS related issues
  website/docs/examples/connections/create-connection.mdx
  website/docs/examples/connections/create-pool.mdx
  website/docs/examples/connections/createPoolCluster.mdx
Labels: documentation
