Repository sidorares/node-mysql2, pull requests merged in 2024-05, with the labels that each got.

#2662 chore(website): update dependecies manually
  website/package-lock.json
  website/package.json
Labels: dependencies

#2699 Fixed typing for caching_sha2_password where misspelt jonServerPublicKey is replaced by onServerPublicKey
  typings/mysql/lib/Auth.d.ts
Labels: typescript

#2702 fix(security): sanitize fields and tables when using nestTables
  lib/helpers.js
  lib/parsers/binary_parser.js
  lib/parsers/text_parser.js
  test/esm/unit/parsers/ensure-safe-binary-fields.test.mjs
  test/esm/unit/parsers/ensure-safe-text-fields.test.mjs
Labels: security

#2707 chore(website): upgrade `packages-update` dependency
  website/.purc.json
  website/package-lock.json
  website/package.json
Labels: dependencies, website

#2714 ci(deno): run the entire test suite with Deno
  .github/workflows/ci-linux.yml
  package-lock.json
  package.json
  test/deno.ts
  test/integration/test-server-close.test.cjs
Labels: deno

#2642 feat: Add jsonStrings configuration
  lib/connection_config.js
  lib/parsers/binary_parser.js
  lib/parsers/text_parser.js
  typings/mysql/lib/Connection.d.ts
  website/docs/documentation/00-index.mdx
Labels: needs tests

#2628 fix(stream): reads should emit the dataset number for each dataset
  lib/commands/query.js
  test/integration/test-multi-result-streaming.test.cjs
Labels: mysqljs-mysql-incompatibilities
