Repository sidorares/node-mysql2, pull requests merged in 2024-11, with the labels that each got.

#3081 fix: circular dependencies
  index.js
  lib/base/connection.js
  lib/base/pool.js
  lib/base/pool_connection.js
  lib/connection.js
  lib/create_connection.js
  lib/create_pool.js
  lib/create_pool_cluster.js
  lib/pool.js
  lib/pool_connection.js
  lib/promise/connection.js
  lib/promise/inherit_events.js
  lib/promise/make_done_cb.js
  lib/promise/pool.js
  lib/promise/pool_connection.js
  lib/promise/prepared_statement_info.js
  promise.js
Labels: refactor

#3209 fix: Deno `v2` requires `commonjs` type explicitly
  .github/workflows/ci-linux.yml
  package.json
Labels: deno

#3249 chore(website): update dependencies manually
  website/package-lock.json
  website/package.json
Labels: dependencies, website
