Repository sidorares/node-mysql2, pull requests merged in 2025-02, with the labels that each got.

#3365 feat(`disableEval`): add static parsers
  .github/workflows/ci-coverage.yml
  .github/workflows/ci-linux.yml
  .nycrc
  lib/commands/execute.js
  lib/commands/query.js
  lib/connection_config.js
  lib/helpers.js
  lib/parsers/static_binary_parser.js
  lib/parsers/static_text_parser.js
  package.json
  test/common.test.cjs
  test/integration/connection/test-nested-tables-query.test.cjs
  test/integration/connection/test-typecast.test.cjs
  test/integration/regressions/test-#433.test.cjs
  typings/mysql/lib/Connection.d.ts
Labels: needs documentation, awaiting approval

#3379 fix(query): support `VECTOR` packets in static parser
  lib/parsers/static_text_parser.js
Labels: mysql v9

#3384 docs: document SSL options
  website/docs/documentation/00-index.mdx
  website/docs/documentation/ssl.mdx
  website/docs/examples/connections/create-connection.mdx
Labels: documentation, good first contribution
