Repository sidorares/node-mysql2, pull requests merged in 2025-09, with the labels that each got.

#3776 feat: gracefully end pool connections #3148
  lib/base/pool.js
  lib/base/pool_connection.js
  lib/connection_config.js
  test/common.test.cjs
  test/integration/graceful-end/test-end-with-default-config.test.cjs
  test/integration/graceful-end/test-end-with-graceful-end-config.test.cjs
  test/integration/graceful-end/test-pool-release-idle-with-default-config.test.cjs
  test/integration/graceful-end/test-pool-release-idle-with-graceful-end-config.test.cjs
  typings/mysql/lib/Connection.d.ts
  website/docs/documentation/extras.mdx
Labels: needs investigation

#3819 fix(typings): missing callback to PoolCluster.end()
  typings/mysql/lib/PoolCluster.d.ts
Labels: typescript

#3831 chore(website): update dependencies manually
  website/package-lock.json
  website/package.json
Labels: website
