Repository sidorares/node-mysql2, pull requests merged in 2025-03, with the labels that each got.

#3261 fix: `PromisePoolCluster.of` returns `PromisePoolCluster` instead of `PoolNamespace`
  lib/promise/pool_cluster.js
  promise.js
  test/esm/integration/pool-cluster/test-promise-wrapper.test.mjs
Labels: good first contribution

#3210 chore: fix typo in `authPluginName` property
  lib/commands/client_handshake.js
  lib/packets/handshake.js
Labels: duplicate

#3455 chore(deps): force update for vulnerable development dependencies
  package-lock.json
Labels: dependencies

#2289 feat: support Cloudflare Workers
  website/docs/documentation/connect-on-cloudflare.mdx
Labels: documentation, good first contribution
